{% set name = "types-cryptography" %}
{% set version = "3.3.6" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/types-cryptography-{{ version }}.tar.gz
  sha256: 3018192812b073fc00eee66bfd8e202e62359e415ec690f41747b2097c1daf40

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python >=3.6
  run:
    - python >=3.6
    - types-enum34
    - types-ipaddress

test:
  commands:
    - test -f $SP_DIR/cryptography-stubs/__init__.pyi


about:
  home: https://github.com/python/typeshed
  summary: Typing stubs for cryptography
  license: Apache-2.0 AND MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - fhoehle
    - conda-forge/mypy
